//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CST.OAT {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.CST.OAT.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Err_ClauseBothDataDictData {
            get {
                return ResourceManager.GetString("Err_ClauseBothDataDictData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseCharactersAfterClosedParentheses {
            get {
                return ResourceManager.GetString("Err_ClauseCharactersAfterClosedParentheses", resourceCulture);
            }
        }
        
        internal static string Err_ClauseCharactersBeforeOpenParentheses {
            get {
                return ResourceManager.GetString("Err_ClauseCharactersBeforeOpenParentheses", resourceCulture);
            }
        }
        
        internal static string Err_ClauseCharactersBetweenClosedParentheses {
            get {
                return ResourceManager.GetString("Err_ClauseCharactersBetweenClosedParentheses", resourceCulture);
            }
        }
        
        internal static string Err_ClauseCharactersBetweenOpenParentheses {
            get {
                return ResourceManager.GetString("Err_ClauseCharactersBetweenOpenParentheses", resourceCulture);
            }
        }
        
        internal static string Err_ClauseCloseParenthesesInNot {
            get {
                return ResourceManager.GetString("Err_ClauseCloseParenthesesInNot", resourceCulture);
            }
        }
        
        internal static string Err_ClauseDictDataUnexpected {
            get {
                return ResourceManager.GetString("Err_ClauseDictDataUnexpected", resourceCulture);
            }
        }
        
        internal static string Err_ClauseDuplicateName {
            get {
                return ResourceManager.GetString("Err_ClauseDuplicateName", resourceCulture);
            }
        }
        
        internal static string Err_ClauseEndsWithOperator {
            get {
                return ResourceManager.GetString("Err_ClauseEndsWithOperator", resourceCulture);
            }
        }
        
        internal static string Err_ClauseExpectedDateTime {
            get {
                return ResourceManager.GetString("Err_ClauseExpectedDateTime", resourceCulture);
            }
        }
        
        internal static string Err_ClauseExpectedInt {
            get {
                return ResourceManager.GetString("Err_ClauseExpectedInt", resourceCulture);
            }
        }
        
        internal static string Err_ClauseExpressionButMissingLabels {
            get {
                return ResourceManager.GetString("Err_ClauseExpressionButMissingLabels", resourceCulture);
            }
        }
        
        internal static string Err_ClauseInvalidLabel {
            get {
                return ResourceManager.GetString("Err_ClauseInvalidLabel", resourceCulture);
            }
        }
        
        internal static string Err_ClauseInvalidLambda__0__1__2_ {
            get {
                return ResourceManager.GetString("Err_ClauseInvalidLambda_{0}{1}{2}", resourceCulture);
            }
        }
        
        internal static string Err_ScriptingDisabled__0__1_ {
            get {
                return ResourceManager.GetString("Err_ScriptingDisabled_{0}{1}", resourceCulture);
            }
        }
        
        internal static string Err_ClauseInvalidNotOperator {
            get {
                return ResourceManager.GetString("Err_ClauseInvalidNotOperator", resourceCulture);
            }
        }
        
        internal static string Err_ClauseInvalidOperator {
            get {
                return ResourceManager.GetString("Err_ClauseInvalidOperator", resourceCulture);
            }
        }
        
        internal static string Err_ClauseInvalidRegex {
            get {
                return ResourceManager.GetString("Err_ClauseInvalidRegex", resourceCulture);
            }
        }
        
        internal static string Err_ClauseMissingCustomOperation {
            get {
                return ResourceManager.GetString("Err_ClauseMissingCustomOperation", resourceCulture);
            }
        }
        
        internal static string Err_ClauseMissingLabels {
            get {
                return ResourceManager.GetString("Err_ClauseMissingLabels", resourceCulture);
            }
        }
        
        internal static string Err_ClauseMissingListData {
            get {
                return ResourceManager.GetString("Err_ClauseMissingListData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseMissingValidationForOperation {
            get {
                return ResourceManager.GetString("Err_ClauseMissingValidationForOperation", resourceCulture);
            }
        }
        
        internal static string Err_ClauseMultipleConsecutiveNots {
            get {
                return ResourceManager.GetString("Err_ClauseMultipleConsecutiveNots", resourceCulture);
            }
        }
        
        internal static string Err_ClauseNoData {
            get {
                return ResourceManager.GetString("Err_ClauseNoData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseNoDataOrDictData {
            get {
                return ResourceManager.GetString("Err_ClauseNoDataOrDictData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseParenthesisInLabel {
            get {
                return ResourceManager.GetString("Err_ClauseParenthesisInLabel", resourceCulture);
            }
        }
        
        internal static string Err_ClauseRedundantData {
            get {
                return ResourceManager.GetString("Err_ClauseRedundantData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseRedundantDictData {
            get {
                return ResourceManager.GetString("Err_ClauseRedundantDictData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseUnbalancedParentheses {
            get {
                return ResourceManager.GetString("Err_ClauseUnbalancedParentheses", resourceCulture);
            }
        }
        
        internal static string Err_ClauseUndefinedLabel {
            get {
                return ResourceManager.GetString("Err_ClauseUndefinedLabel", resourceCulture);
            }
        }
        
        internal static string Err_ClauseUnexpectedDictData {
            get {
                return ResourceManager.GetString("Err_ClauseUnexpectedDictData", resourceCulture);
            }
        }
        
        internal static string Err_ClauseUnsuppportedOperator__0__1__2__3_ {
            get {
                return ResourceManager.GetString("Err_ClauseUnsuppportedOperator_{0}{1}{2}{3}", resourceCulture);
            }
        }
        
        internal static string Err_ClauseUnusedLabel {
            get {
                return ResourceManager.GetString("Err_ClauseUnusedLabel", resourceCulture);
            }
        }
        
        internal static string Err_ValidationDelegateUndefined__0__1__2_ {
            get {
                return ResourceManager.GetString("Err_ValidationDelegateUndefined_{0}{1}{2}", resourceCulture);
            }
        }
        
        internal static string Err_NoOperation__0__1_ {
            get {
                return ResourceManager.GetString("Err_NoOperation_{0}{1}", resourceCulture);
            }
        }
    }
}
