# Azure Pipelines
# https://aka.ms/yaml

name: OAT_PR_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: SecurityEngineering/OSS-Tools-Pipeline-Templates
      ref: refs/tags/v1.0.6

stages:
- stage: Test
  dependsOn: []
  jobs:
  - template: dotnet-test-job.yml@templates
    parameters:
      jobName: 'dotnet_test_windows'
      dotnetVersion: 7.0.x
      dotnetVersionLTS: 6.0.x
      vmImage: 'oss-tools-win2022_1es-managed'
      projectPath: 'OAT.Tests/OAT.Tests.csproj'
  - template: dotnet-test-job.yml@templates
    parameters:
      jobName: 'dotnet_test_ubuntu'
      dotnetVersion: 7.0.x
      dotnetVersionLTS: 6.0.x
      vmImage: 'ubuntu-22.04-image-base'
      projectPath: 'OAT.Tests/OAT.Tests.csproj'

- stage: SDL
  dependsOn: []
  jobs:
  - template: sdl-job.yml@templates

- stage: Build
  dependsOn:
  - Test
  jobs:
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_lib'
      buildConfiguration: 'Release'
      dotnetVersion: '7.0.x'
      projectPath: 'OAT/OAT.csproj'
      projectName: 'OAT'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_scripting'
      buildConfiguration: 'Release'
      dotnetVersion: '7.0.x'
      projectPath: 'OAT.Scripting/OAT.Scripting.csproj'
      projectName: 'OAT_Scripting'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_blazor'
      buildConfiguration: 'Release'
      dotnetVersion: '7.0.x'
      projectPath: 'OAT.Blazor.Components/OAT.Blazor.Components.csproj'
      projectName: 'OAT_Blazor_Components'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
