# Azure Pipelines
# https://aka.ms/yaml

name: OAT_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - OAT
    - OAT.Blazor
    - OAT.Blazor.Components
    - OAT.Scripting
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: SecurityEngineering/OSS-Tools-Pipeline-Templates
      ref: refs/tags/v1.1.0

variables:
  BuildConfiguration: 'Release'
  DotnetVersion: '8.0.x'

stages:
- stage: Test
  dependsOn: []
  jobs:
  - template: dotnet-test-job.yml@templates
    parameters:
      jobName: 'dotnet_test_windows'
      dotnetVersions: ['6.0.x','7.0.x','8.0.x']
      vmImage: 'oss-tools-win2022_1es-managed'
      projectPath: 'OAT.Tests/OAT.Tests.csproj'
  - template: dotnet-test-job.yml@templates
    parameters:
      jobName: 'dotnet_test_ubuntu'
      dotnetVersions: ['6.0.x','7.0.x','8.0.x']
      vmImage: 'ubuntu-22.04-image-base'
      projectPath: 'OAT.Tests/OAT.Tests.csproj'

- stage: SDL
  dependsOn: []
  jobs:
  - template: sdl-job.yml@templates

- stage: Build
  dependsOn:
  - Test
  jobs:
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_lib'
      buildConfiguration: ${{ variables.BuildConfiguration }}
      dotnetVersion: ${{ variables.DotnetVersion }}
      projectPath: 'OAT/OAT.csproj'
      projectName: 'OAT'
      customPackFlags: '/p:ContinuousIntegrationBuild=true'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_scripting'
      buildConfiguration: ${{ variables.BuildConfiguration }}
      dotnetVersion: ${{ variables.DotnetVersion }}
      projectPath: 'OAT.Scripting/OAT.Scripting.csproj'
      projectName: 'OAT_Scripting'
      customPackFlags: '/p:ContinuousIntegrationBuild=true'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_blazor'
      buildConfiguration: ${{ variables.BuildConfiguration }}
      dotnetVersion: ${{ variables.DotnetVersion }}
      projectPath: 'OAT.Blazor.Components/OAT.Blazor.Components.csproj'
      projectName: 'OAT_Blazor_Components'
      customPackFlags: '/p:ContinuousIntegrationBuild=true'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates

- stage: Release
  dependsOn:
  - SDL
  - Build
  condition: succeeded()
  jobs:
  - job: sign_hash_release
    displayName: Code Sign, Generate Hashes, Publish Public Releases
    pool:
      name: 'OSS-Tools-1ESPool'
      vmImage: 'oss-tools-win2022_1es-managed'
    steps:
    - task: UseDotNet@2 
      inputs:
        packageType: 'sdk'
        version: '6.0.x' # ESRP requires a specific version. Do not re-use variable.
    - template: nbgv-set-version-steps.yml@templates
    - task: DownloadBuildArtifacts@0
      displayName: Download Unsigned Archives
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: 'Unsigned_Binaries/*.zip'
        downloadPath: '$(Build.BinariesDirectory)'
    - task: ExtractFiles@1
      displayName: Extract Artifacts for Signing
      inputs:
        archiveFilePatterns: '$(Build.BinariesDirectory)\Unsigned_Binaries\*.zip'
        destinationFolder: '$(Build.BinariesDirectory)'
        cleanDestinationFolder: false
        overwriteExistingFiles: true
    - task: AntiMalware@4
      displayName: Anti-Malware Scan
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.BinariesDirectory)'
        EnableServices: true
        SupportLogOnError: true
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Warning'
    - task: EsrpCodeSigning@3
      displayName: Code Sign Nuget Packages
      inputs:
        ConnectedServiceName: 'OAT_CodeSign'
        FolderPath: '$(Build.BinariesDirectory)'
        Pattern: '*.nupkg, *.snupkg'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [
                  {
                      "KeyCode" : "CP-401405",
                      "OperationCode" : "NuGetSign",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  },
                  {
                      "KeyCode" : "CP-401405",
                      "OperationCode" : "NuGetVerify",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  }
              ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'
    - powershell: 'Get-ChildItem -Path ''$(Build.BinariesDirectory)'' -Recurse CodeSign* | foreach { Remove-Item -Path $_.FullName }'
      displayName: 'Delete Code Sign Summaries'
    - task: PowerShell@2
      displayName: Move NuGet Packages
      inputs:
        targetType: 'inline'
        script: |
          mv $env:BUILD_BINARIESDIRECTORY/*.nupkg $env:BUILD_STAGINGDIRECTORY/
          mv $env:BUILD_BINARIESDIRECTORY/*.snupkg $env:BUILD_STAGINGDIRECTORY/
    - task: PublishPipelineArtifact@1
      displayName: Pipeline Publish Signed Artifacts
      inputs:
        targetPath: '$(Build.StagingDirectory)'
        artifact: 'Signed_Binaries'
    - task: NuGetCommand@2
      displayName: Publish NuGet Packages
      inputs:
        command: 'push'
        packagesToPush: '$(Build.StagingDirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'CST-E Nuget CI'
        verbosityPush: 'Normal'
