name: Publish GH - Pages

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet publish OAT.Blazor -c Release -f net7.0
    - name: Mkdir toPublish
      run: mkdir toPublish
    - name: Move Blazor Output into Place
      run: mv OAT.Blazor/bin/Release/net8.0/publish/wwwroot toPublish/Blazor
    - name: Update gitattributes
      run: mv toPublish/Blazor/gitattributes toPublish/Blazor/.gitattributes

    - name: Install chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - name: Install docfx
      run: choco install docfx
    - name: Run DocFx
      run: docfx docfx/docfx.json
    - name: Move DocFx Output Into Place
      run: mv docfx/_site/* toPublish/

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: toPublish
